### ISSUE TITLE
improve immediate loading efficiency

### ISSUE THREAD

**Issue by jo-he** [aoh/owl-lisp#88]
There already is a two-byte instruction for loading `0 '() #t #f`. But measuring shows that `1` is more often needed than `#t` – by factor 2.9 on jumps and 2.6 on loads (with loads, even more often than `0`).

At the same time, the existing three-byte instruction for loading fixnums does not use the available bit space efficiently. With the opcode byte and one constant argument, we have ten bits available. One for the sign, and nine for the number itself. Having `0` and `1` as a short instruction, we could use this to load the integers { -512, ..., -1, 2, ..., 513 }.

**Comment by aoh** [comment]
Neat. I like the bit twiddling.

**Comment by jo-he** [comment]
The benefit of having a two-byte loading instruction for loading `1` does not outweigh the drawback of not being able to directly load `#t` any longer. Tests with Owl itself showed, that the fasl size increases too much.
