### ISSUE TITLE
Consider getting rid of the bind instruction

### ISSUE THREAD

**Issue by aoh** [aoh/owl-lisp#89]
Tuples are used to hold several values together. Values can be indexed by offsets, but more often than not there are a known numbers of values along with a type tag for use as tagged unions (or sum types).

The bind primop is used to load values of a tuple into registers, or in other words, to call a function with the contents of a tuple. There is a more and a less obvious way to get rid of this primop:
1. Allow `apply` to take tuples as arguments in addition to lists, so that `(bind tuple func)` = `(apply func tuple)`
2. The λ-calculus definition of e.g. 2-tuples is typically `λabc.(cab)`, in which case `car` can be defined as `λt.(t λab.a)`. Along these lines, one could define tuples also in Owl as `(define ((triple a b c) s) (s a b c))`. For such tuples, it would be the case that `(bind tuple func)` = `(tuple func)` as such. Would this be a reasonable semantic interpretation for calling a tuple?

**Comment by jo-he** [comment]
Since tuples and lists are easily convertible, I was thinking about getting rid of either `apply` or `bind`, too. Because list -> tuple has less overhead, I'd vote for a VM instruction that takes tuples only. That way we would save some C code, and the Scheme `apply` could then be implemented on Owl side by calling `listuple`, followed by an advanced `bind` (the current one seems to work on lambdas only).

The current op usage statistic (from running `make fasl/ol.fasl`) would confirm this choice:
```
01 7599860684
34 3946229377
02 3081751502
16 2450182100
05 1821048250
04 1489964011
14 1349078289
54 1309331305
15 1117832484
09 1051701387
08 889083175
24 855594044
41 697966242
47 472301458
13 406486896
55 373058177
51 293105783
44 272458236
49 223369577
38 107659290
42 106822399
32 101604814
45 77924698
36 71017391
43 68355986
23 59566193
40 45350939
28 40751409
58 18898069
56 14753524
39 12785849
26 11596251
25 6148654
50 4844253
27 4409992
57 2464667
37 897451
35 568833
63 125663
62 44690
61 1189
60 179
```
`apply` (currently 60 + 61) is called 1,368 times, while `bind` (op 32) is called 101,604,814 times!

**Comment by aoh** [comment]
Bind is surprisingly heavily used! It's probably a lot less used in other programs, though, since the compiler is doing a lot of AST walking.

A tuple-based bind would otherwise be a good idea. It would have the drawback of having to unwind the entire argument list at each step, which might cause some applications to go quadratic by surprise. This may sound bad, but I'm actually also considering an option of kind of going this route, but detecting such cases at runtime.

This is still at ponder stage, and semantic changes are extremely important to ponder thoroughly before taking action, so it makes sense to try to consider all options. What if we eliminated both apply *and* bind?

Obviously there is a Turing tarpit nearby tempting all structures to be implemented in terms of functions, which are perfectly capable of expressing anything. This is not a bad direction to move towards or at least getting inspiration from.

Based on a quick benchmark, an approach for encoding AST nodes and working on them based on LC (https://github.com/owl-lisp/owl/blob/develop/owl/sum.scm#L16) is in fact already faster than constructing tuples and dispatching based on the first element of them. An additional bonus here is that it could be made a compile time error to try to use such sum type nodes without explicitly taking into account all the possibilities or explicitly ignoring them. Combining this and the simpler case of not having a type tag, only working as a binding node, not only would get rid of the bind instruction, but it would do so while improving efficiency and making compile time error detection easier without the need of a non-trivial type system.

That leaves `apply`. It's a core LISP thing, so I feel somewhat uneasy about touching it, but let's give it a thought. Apply is there and makes sense, because initially arguments were always stored as argument *lists*. This is no longer the case. Also, in my experience, if you end up using apply, you're probably doing something wrong. R7RS has `case-lambda`, so apply could be defined up to n arguments by having a `case-lambda` which unwinds the list and calls the given function the suitable number of arguments. I'd bet a few argments takes care of 80% of uses of `apply`, and the 20% should really be using a `fold` or `foldr` instead.

**Comment by jo-he** [comment]
The LC based approach sounds interesting, although I don't get it fully, yet (will need a quiet minute for this). So currently I would base the decision on the benchmark and the amount of code. (-;

Regarding `apply` you're probably right – I for my part have always tried to avoid using it. Maybe we should phase it out step by step, so we could rebase it on tuples first (with the help of `listuple`), to already get rid of `bind` (just thinking, what I nice `cast` replacement `(apply-tuple mkt t obj)` would be – although this is currently not needed).

**Comment by aoh** [comment]
Looks like I'll have some unexpected spare time today. Let's see what happens. Removing the current `apply` would remove a special case from all over the compiler, so that would be a tempting option. A first quick test could be to try to bootstrap without using apply, and if successful, see how that affects performance.

**Comment by aoh** [comment]
That seemed to be surprisingly easy. After replacing apply and apply-cont with cases that handle arity up to a (sensible for typical use) maximum, one can remove both instructions from the VM. Heap seems to get built this way a around 1% faster, there are 3M words written less, but the heap is a few hundred bytes larger, mainly due to having defined the wrapper functions. 

I also spotted bad use of apply in the code and replaced it with a fold. Seems to work :)

**Comment by jo-he** [comment]
Fantastic. Step by step Owl becomes a masterpiece of simplicity. :+1:

**Comment by aoh** [comment]
You have also done a great job in pushing Owl to that direction. :+1:

**Comment by jo-he** [comment]
Thanks (-:

**Comment by aoh** [comment]
Closing, as development and issue tracking now happens at gitlab.com.
