### ISSUE TITLE
Look into Github alternatives

### ISSUE THREAD

**Issue by aoh** [aoh/owl-lisp#91]
Apparently Microsoft is about to buy Github.

**Comment by jo-he** [comment]
Might be quite easy to switch to https://about.gitlab.com/

But why?

At the end, every successful company is endangered being bought by a bigger one. And using a free service does not support a company (except for publicity maybe), but should do more harm (by using resources).

And Microsoft isn't _that_ bad anymore. I would be much more concerned, if GitHub would be bought by Oracle.

**Comment by aoh** [comment]
Github was a relatively netural site for sharing code. If they had trouble making the ends meet, they could have for example made the current financial status more open and encourage users and organizations to pitch in. Selling such a site to any single commercial player is, in my opinion, a bad move.

As to Microsoft... Nokia used to be a big thing here in Finland. I used to have a Nokia phone that could for example run a full chrooted Linux system alongside the phone software on the same kernel. I was able to ssh to remote machines, run owl prototypes, make, gcc, git, gdb, strace, top, tmux, screen, irssi, mailx, trn, vi, emacs, play with various schemes and even run graphical applications. There is probably still code in Owl written on a Nokia N810. This was *over ten years ago*. Then Microsoft came to town, bought Nokia, axed all Linux phones and turned Nokia into a Windows phone factory.

This isn't the only only thing, but it alone is enough for me.

Gitlab seems like a good option, especially with plans about fedarated operation.

**Comment by jo-he** [comment]
Okay, I see your reasons now. The Nokia story is really too bad.

**Comment by aoh** [comment]
Gitlab seems like a good choice. @jo-he, do you have an account there?

**Comment by jo-he** [comment]
Not yet. But if you move Owl Lisp development there, I will create one.

**Comment by aoh** [comment]
Yes, Gitlab seems to have a good set of features and a nice open mentality. Let's try it out. Let me know when you have an account.

**Comment by jo-he** [comment]
I'm now at https://gitlab.com/jo.h

**Comment by jo-he** [comment]
Not really surprisingly, there seems to be a trend moving towards GitLab now: https://about.gitlab.com/2018/06/03/movingtogitlab/ (-;

What are your plans regarding the GitHub presence? I think, with the next Owl release latest, we should empty the repository here, and just leave a README.md pointing to https://gitlab.com/owl-lisp/owl – otherwise people (like distribution packagers) could get confused where to find the latest version.

**Comment by aoh** [comment]
Yes, that would be a good approach :+1: This can be closed now that a suitable new home has been found.
