### ISSUE TITLE
consider using dotted lists with bignum arithmetic

### ISSUE THREAD

**Issue by jo-he** [aoh/owl-lisp#92]
In a dotted (improper) list, `cdr` would be either of type-fix or of type-int – like the root. That way, creation and calculation could be simplified, and it would save three words on the heap for every bignum.

This would probably require the introduction of a new type. Would be good, if signedness could be checked for type-fix and type-int in the same way, e. g. via `(eq? (fxband (type number) 32) 32)`.

…or maybe it would be sufficient to have just one type-int (and the root node decides about the signedness: via `type-fix+` or `type-fix-`.

**Comment by aoh** [comment]
This could be a good approach. I'd vote to keep the sign in root node type instead of the first digit, because otherwise you could not assume all digits to be positive.

**Comment by aoh** [comment]
Closing, as development and issue tracking now happens at gitlab.com.
